// <auto-generated />
using System;
using Librarium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Librarium.Migrations
{
    [DbContext(typeof(LibrariumDbContext))]
    [Migration("20260503133556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Librarium.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtpCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Librarium.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Librarium.Models.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("Librarium.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("Librarium.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Librarium.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Librarium.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BorrowRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReturnRequests");
                });

            modelBuilder.Entity("Librarium.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridCol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShelfType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GridCol = 3,
                            GridRow = 1,
                            ShelfCode = "A1",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 2,
                            GridCol = 4,
                            GridRow = 1,
                            ShelfCode = "A2",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 3,
                            GridCol = 5,
                            GridRow = 1,
                            ShelfCode = "A3",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 4,
                            GridCol = 6,
                            GridRow = 1,
                            ShelfCode = "A4",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 5,
                            GridCol = 7,
                            GridRow = 1,
                            ShelfCode = "A5",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 6,
                            GridCol = 8,
                            GridRow = 1,
                            ShelfCode = "A6",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 7,
                            GridCol = 9,
                            GridRow = 1,
                            ShelfCode = "A7",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 8,
                            GridCol = 10,
                            GridRow = 1,
                            ShelfCode = "A8",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 9,
                            GridCol = 3,
                            GridRow = 2,
                            ShelfCode = "A9",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 10,
                            GridCol = 4,
                            GridRow = 2,
                            ShelfCode = "A10",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 11,
                            GridCol = 5,
                            GridRow = 2,
                            ShelfCode = "A11",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 12,
                            GridCol = 6,
                            GridRow = 2,
                            ShelfCode = "A12",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 13,
                            GridCol = 7,
                            GridRow = 2,
                            ShelfCode = "A13",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 14,
                            GridCol = 8,
                            GridRow = 2,
                            ShelfCode = "A14",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 15,
                            GridCol = 9,
                            GridRow = 2,
                            ShelfCode = "A15",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 16,
                            GridCol = 10,
                            GridRow = 2,
                            ShelfCode = "A16",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 17,
                            GridCol = 3,
                            GridRow = 4,
                            ShelfCode = "A17",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 18,
                            GridCol = 4,
                            GridRow = 4,
                            ShelfCode = "A18",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 19,
                            GridCol = 5,
                            GridRow = 4,
                            ShelfCode = "A19",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 20,
                            GridCol = 6,
                            GridRow = 4,
                            ShelfCode = "A20",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 21,
                            GridCol = 7,
                            GridRow = 4,
                            ShelfCode = "A21",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 22,
                            GridCol = 8,
                            GridRow = 4,
                            ShelfCode = "A22",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 23,
                            GridCol = 9,
                            GridRow = 4,
                            ShelfCode = "A23",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 24,
                            GridCol = 3,
                            GridRow = 5,
                            ShelfCode = "A24",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 25,
                            GridCol = 4,
                            GridRow = 5,
                            ShelfCode = "A25",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 26,
                            GridCol = 5,
                            GridRow = 5,
                            ShelfCode = "A26",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 27,
                            GridCol = 6,
                            GridRow = 5,
                            ShelfCode = "A27",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 28,
                            GridCol = 7,
                            GridRow = 5,
                            ShelfCode = "A28",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 29,
                            GridCol = 8,
                            GridRow = 5,
                            ShelfCode = "A29",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 30,
                            GridCol = 9,
                            GridRow = 5,
                            ShelfCode = "A30",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 31,
                            GridCol = 3,
                            GridRow = 10,
                            ShelfCode = "A31",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 32,
                            GridCol = 4,
                            GridRow = 10,
                            ShelfCode = "A32",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 33,
                            GridCol = 5,
                            GridRow = 10,
                            ShelfCode = "A33",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 34,
                            GridCol = 6,
                            GridRow = 10,
                            ShelfCode = "A34",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 35,
                            GridCol = 7,
                            GridRow = 10,
                            ShelfCode = "A35",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 36,
                            GridCol = 8,
                            GridRow = 10,
                            ShelfCode = "A36",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 37,
                            GridCol = 1,
                            GridRow = 4,
                            ShelfCode = "A37",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 38,
                            GridCol = 1,
                            GridRow = 5,
                            ShelfCode = "A38",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 39,
                            GridCol = 1,
                            GridRow = 6,
                            ShelfCode = "A39",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 40,
                            GridCol = 1,
                            GridRow = 7,
                            ShelfCode = "A40",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 41,
                            GridCol = 1,
                            GridRow = 8,
                            ShelfCode = "A41",
                            ShelfType = "almirah"
                        },
                        new
                        {
                            Id = 42,
                            GridCol = 3,
                            GridRow = 7,
                            ShelfCode = "R42",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 43,
                            GridCol = 4,
                            GridRow = 7,
                            ShelfCode = "R43",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 44,
                            GridCol = 5,
                            GridRow = 7,
                            ShelfCode = "R44",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 45,
                            GridCol = 6,
                            GridRow = 7,
                            ShelfCode = "R45",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 46,
                            GridCol = 7,
                            GridRow = 7,
                            ShelfCode = "R46",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 47,
                            GridCol = 3,
                            GridRow = 8,
                            ShelfCode = "R47",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 48,
                            GridCol = 4,
                            GridRow = 8,
                            ShelfCode = "R48",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 49,
                            GridCol = 5,
                            GridRow = 8,
                            ShelfCode = "R49",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 50,
                            GridCol = 6,
                            GridRow = 8,
                            ShelfCode = "R50",
                            ShelfType = "rack"
                        },
                        new
                        {
                            Id = 51,
                            GridCol = 7,
                            GridRow = 8,
                            ShelfCode = "R51",
                            ShelfType = "rack"
                        });
                });

            modelBuilder.Entity("Librarium.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtpCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Librarium.Models.Book", b =>
                {
                    b.HasOne("Librarium.Models.Shelf", "Shelf")
                        .WithMany("Books")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Librarium.Models.BookingRequest", b =>
                {
                    b.HasOne("Librarium.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Librarium.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Librarium.Models.BorrowRecord", b =>
                {
                    b.HasOne("Librarium.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Librarium.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Librarium.Models.Notification", b =>
                {
                    b.HasOne("Librarium.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Librarium.Models.Shelf", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
